name: Lint, test, and deploy
on:
  push:
    paths-ignore:
      - "events-deep-dive"
jobs:
  run_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm i
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: deploy
        run: npm run deploy
